//catch block in another catch block not possible==syntax error

package Exception;

public class trycatchcatch2 {
	
	public static void main(String[] args) {
		
//		int a=10;
//		int b=0;
//		int c=0;
//		int d[] = {12,34,45,65,67};
//		
//		
//		try 
//		{
//			System.out.println("risky code");
//			c=a/b;                            
//			System.out.println(d[6]);          
//			
//		}
//
//		
//		catch(ArithmeticException e)
//		{
//			System.out.println("alternative code of arithematic");
//			b=2;
//			c=a/b;
//		
//		
//		catch(ArrayIndexOutOfBoundsException e)
//		{
//			System.out.println("alternative code of array");
//			System.out.println(d[2]);
//		}
//		
//		}
//		
//		System.out.println(c); //normal flow

	}

}
